// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"
	api "phudt/week4/internal/api"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// PatientServiceClient is an autogenerated mock type for the PatientServiceClient type
type PatientServiceClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, in, opts
func (_m *PatientServiceClient) Add(ctx context.Context, in *api.AddRequest, opts ...grpc.CallOption) (*api.Patient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *api.Patient
	if rf, ok := ret.Get(0).(func(context.Context, *api.AddRequest, ...grpc.CallOption) *api.Patient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Patient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.AddRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
