// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"
	api "phudt/week4/internal/api"

	mock "github.com/stretchr/testify/mock"
)

// PatientServiceServer is an autogenerated mock type for the PatientServiceServer type
type PatientServiceServer struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *PatientServiceServer) Add(_a0 context.Context, _a1 *api.AddRequest) (*api.Patient, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *api.Patient
	if rf, ok := ret.Get(0).(func(context.Context, *api.AddRequest) *api.Patient); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Patient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.AddRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPatientServiceServer provides a mock function with given fields:
func (_m *PatientServiceServer) mustEmbedUnimplementedPatientServiceServer() {
	_m.Called()
}
