// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/note.proto

/*
Package note is a generated protocol buffer package.

It is generated from these files:
	proto/note.proto

It has these top-level messages:
	Note
	NoteReq
	NoteFindReq
	NoteDelReq
	NoteDelRes
*/
package note

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Note struct {
	Id        int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
	// bool complete = 3; // Only change the name
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Note) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Note) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Note) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NoteReq struct {
	Title     string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
}

func (m *NoteReq) Reset()                    { *m = NoteReq{} }
func (m *NoteReq) String() string            { return proto.CompactTextString(m) }
func (*NoteReq) ProtoMessage()               {}
func (*NoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NoteReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoteReq) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type NoteFindReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *NoteFindReq) Reset()                    { *m = NoteFindReq{} }
func (m *NoteFindReq) String() string            { return proto.CompactTextString(m) }
func (*NoteFindReq) ProtoMessage()               {}
func (*NoteFindReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NoteFindReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NoteDelReq struct {
	Id int32 `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
}

func (m *NoteDelReq) Reset()                    { *m = NoteDelReq{} }
func (m *NoteDelReq) String() string            { return proto.CompactTextString(m) }
func (*NoteDelReq) ProtoMessage()               {}
func (*NoteDelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NoteDelReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NoteDelRes struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *NoteDelRes) Reset()                    { *m = NoteDelRes{} }
func (m *NoteDelRes) String() string            { return proto.CompactTextString(m) }
func (*NoteDelRes) ProtoMessage()               {}
func (*NoteDelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NoteDelRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NoteDelRes) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Note)(nil), "note.Note")
	proto.RegisterType((*NoteReq)(nil), "note.NoteReq")
	proto.RegisterType((*NoteFindReq)(nil), "note.NoteFindReq")
	proto.RegisterType((*NoteDelReq)(nil), "note.NoteDelReq")
	proto.RegisterType((*NoteDelRes)(nil), "note.NoteDelRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NoteService service

type NoteServiceClient interface {
	Create(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*Note, error)
	Find(ctx context.Context, in *NoteFindReq, opts ...grpc.CallOption) (*Note, error)
	// rpc Find(NoteFindReq) returns (Note) {
	//   option (google.api.http) = {
	//     get: "/v1/note/{id}"
	//   };
	// }
	Delete(ctx context.Context, in *NoteDelReq, opts ...grpc.CallOption) (*NoteDelRes, error)
}

type noteServiceClient struct {
	cc *grpc.ClientConn
}

func NewNoteServiceClient(cc *grpc.ClientConn) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) Create(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := grpc.Invoke(ctx, "/note.NoteService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) Find(ctx context.Context, in *NoteFindReq, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := grpc.Invoke(ctx, "/note.NoteService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) Delete(ctx context.Context, in *NoteDelReq, opts ...grpc.CallOption) (*NoteDelRes, error) {
	out := new(NoteDelRes)
	err := grpc.Invoke(ctx, "/note.NoteService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoteService service

type NoteServiceServer interface {
	Create(context.Context, *NoteReq) (*Note, error)
	Find(context.Context, *NoteFindReq) (*Note, error)
	// rpc Find(NoteFindReq) returns (Note) {
	//   option (google.api.http) = {
	//     get: "/v1/note/{id}"
	//   };
	// }
	Delete(context.Context, *NoteDelReq) (*NoteDelRes, error)
}

func RegisterNoteServiceServer(s *grpc.Server, srv NoteServiceServer) {
	s.RegisterService(&_NoteService_serviceDesc, srv)
}

func _NoteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.NoteService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Create(ctx, req.(*NoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteFindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.NoteService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Find(ctx, req.(*NoteFindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteDelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.NoteService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Delete(ctx, req.(*NoteDelReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "note.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NoteService_Create_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _NoteService_Find_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NoteService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/note.proto",
}

func init() { proto.RegisterFile("proto/note.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4e, 0xa4, 0x40,
	0x14, 0x9e, 0x62, 0xa0, 0x7f, 0x5e, 0x77, 0x4f, 0x7a, 0x2a, 0xb3, 0x20, 0xa4, 0x27, 0x43, 0x98,
	0x4c, 0x86, 0xcc, 0x02, 0x92, 0x9e, 0x95, 0x0b, 0x13, 0x3b, 0x76, 0xdc, 0x18, 0x5d, 0xa0, 0xfb,
	0x0e, 0x0d, 0xcf, 0x4e, 0x25, 0x40, 0x21, 0x55, 0xed, 0xc6, 0xb8, 0xf1, 0x0a, 0x1e, 0xc0, 0xab,
	0x78, 0x07, 0xaf, 0xe0, 0x41, 0x4c, 0x15, 0x20, 0x86, 0xc4, 0xb8, 0xab, 0xf7, 0xfd, 0x14, 0xdf,
	0xf7, 0x0a, 0x98, 0x97, 0x15, 0x97, 0x3c, 0x2c, 0xb8, 0xc4, 0x40, 0x1f, 0xa9, 0xa9, 0xce, 0xce,
	0xaf, 0x1d, 0xe7, 0xbb, 0x0c, 0x43, 0x8d, 0x6d, 0xf7, 0x57, 0xa1, 0x64, 0x39, 0x0a, 0x19, 0xe7,
	0x65, 0x2d, 0x73, 0x16, 0x8d, 0x20, 0x2e, 0x59, 0x18, 0x17, 0x05, 0x97, 0xb1, 0x64, 0xbc, 0x10,
	0x35, 0xeb, 0x3d, 0x11, 0x30, 0xcf, 0xb9, 0x44, 0xfa, 0x0d, 0x0c, 0x96, 0xda, 0xc4, 0x25, 0xbe,
	0x15, 0x19, 0x2c, 0xa5, 0x3f, 0xc0, 0x92, 0x4c, 0x66, 0x68, 0x1b, 0x2e, 0xf1, 0xc7, 0x51, 0x3d,
	0xd0, 0x05, 0x8c, 0x13, 0x9e, 0x97, 0x19, 0x4a, 0x4c, 0xed, 0xaf, 0x2e, 0xf1, 0x47, 0x51, 0x07,
	0xd0, 0x03, 0x80, 0xa4, 0xc2, 0x58, 0x62, 0xba, 0x89, 0xa5, 0x6d, 0xba, 0xc4, 0x9f, 0x2c, 0x9d,
	0xa0, 0xfe, 0x7e, 0xd0, 0x06, 0x0c, 0x2e, 0xdb, 0x80, 0xd1, 0xb8, 0x51, 0xaf, 0xa4, 0xb2, 0xee,
	0xcb, 0xb4, 0xb5, 0x5a, 0x9f, 0x5b, 0x1b, 0xf5, 0x4a, 0x7a, 0x87, 0x30, 0x54, 0x0d, 0x22, 0xbc,
	0xee, 0x42, 0x93, 0x0f, 0x43, 0x1b, 0xbd, 0xd0, 0xde, 0x4f, 0x98, 0x28, 0xfb, 0x09, 0x2b, 0x52,
	0x75, 0x45, 0x6f, 0x0f, 0xde, 0x02, 0x40, 0xd1, 0x6b, 0xcc, 0x3a, 0xd6, 0x7a, 0x63, 0x4f, 0xdf,
	0xb1, 0x82, 0xda, 0x30, 0x14, 0xfb, 0x24, 0x41, 0x21, 0xf4, 0x05, 0xa3, 0xa8, 0x1d, 0xe9, 0x6f,
	0x98, 0x61, 0x55, 0xf1, 0x6a, 0x93, 0xa3, 0x10, 0xf1, 0xae, 0xdd, 0xea, 0x54, 0x83, 0x67, 0x35,
	0xb6, 0x7c, 0x24, 0x75, 0x94, 0x0b, 0xac, 0x6e, 0x58, 0x82, 0xf4, 0x0f, 0x0c, 0x8e, 0xf5, 0x82,
	0xe8, 0x2c, 0xd0, 0xef, 0xde, 0xd4, 0x74, 0xa0, 0x1b, 0xbd, 0x2f, 0xf4, 0x2f, 0x98, 0x2a, 0x3c,
	0xfd, 0xde, 0xa1, 0x4d, 0x99, 0x9e, 0xf0, 0x08, 0x06, 0x6b, 0x54, 0xa5, 0xe9, 0xbc, 0xc3, 0xeb,
	0x62, 0x4e, 0x1f, 0x11, 0x1e, 0xbd, 0x7f, 0x7e, 0x79, 0x30, 0xa6, 0xff, 0x40, 0xff, 0x73, 0xe1,
	0x2d, 0x4b, 0xef, 0xb6, 0x03, 0xfd, 0x12, 0xff, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x10, 0x6c,
	0x7a, 0xf1, 0x8d, 0x02, 0x00, 0x00,
}
