// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/note.proto

/*
Package note is a generated protocol buffer package.

It is generated from these files:
	proto/note.proto

It has these top-level messages:
	Note
	NoteCreateReq
*/
package note

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for NoteService service

type NoteService interface {
	Create(ctx context.Context, in *NoteCreateReq, opts ...client.CallOption) (*Note, error)
}

type noteService struct {
	c    client.Client
	name string
}

func NewNoteService(name string, c client.Client) NoteService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "note"
	}
	return &noteService{
		c:    c,
		name: name,
	}
}

func (c *noteService) Create(ctx context.Context, in *NoteCreateReq, opts ...client.CallOption) (*Note, error) {
	req := c.c.NewRequest(c.name, "NoteService.Create", in)
	out := new(Note)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoteService service

type NoteServiceHandler interface {
	Create(context.Context, *NoteCreateReq, *Note) error
}

func RegisterNoteServiceHandler(s server.Server, hdlr NoteServiceHandler, opts ...server.HandlerOption) error {
	type noteService interface {
		Create(ctx context.Context, in *NoteCreateReq, out *Note) error
	}
	type NoteService struct {
		noteService
	}
	h := &noteServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NoteService{h}, opts...))
}

type noteServiceHandler struct {
	NoteServiceHandler
}

func (h *noteServiceHandler) Create(ctx context.Context, in *NoteCreateReq, out *Note) error {
	return h.NoteServiceHandler.Create(ctx, in, out)
}
