// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/note.proto

/*
Package note is a generated protocol buffer package.

It is generated from these files:
	proto/note.proto

It has these top-level messages:
	Note
	NoteCreateReq
*/
package note

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Note struct {
	Id        uint32                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Completed bool                       `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Note) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Note) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Note) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NoteCreateReq struct {
	Title     string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
}

func (m *NoteCreateReq) Reset()                    { *m = NoteCreateReq{} }
func (m *NoteCreateReq) String() string            { return proto.CompactTextString(m) }
func (*NoteCreateReq) ProtoMessage()               {}
func (*NoteCreateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NoteCreateReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoteCreateReq) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*Note)(nil), "note.Note")
	proto.RegisterType((*NoteCreateReq)(nil), "note.NoteCreateReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NoteService service

type NoteServiceClient interface {
	Create(ctx context.Context, in *NoteCreateReq, opts ...grpc.CallOption) (*Note, error)
}

type noteServiceClient struct {
	cc *grpc.ClientConn
}

func NewNoteServiceClient(cc *grpc.ClientConn) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) Create(ctx context.Context, in *NoteCreateReq, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := grpc.Invoke(ctx, "/note.NoteService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoteService service

type NoteServiceServer interface {
	Create(context.Context, *NoteCreateReq) (*Note, error)
}

func RegisterNoteServiceServer(s *grpc.Server, srv NoteServiceServer) {
	s.RegisterService(&_NoteService_serviceDesc, srv)
}

func _NoteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.NoteService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Create(ctx, req.(*NoteCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "note.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NoteService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/note.proto",
}

func init() { proto.RegisterFile("proto/note.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x4d, 0xed, 0x2e, 0xf6, 0x2d, 0x2b, 0x12, 0x3d, 0x94, 0x22, 0x58, 0x7a, 0x0a, 0x08,
	0x29, 0xac, 0x27, 0xbd, 0x2d, 0x7b, 0xf7, 0x10, 0xbd, 0x4b, 0xb7, 0x79, 0x2e, 0x81, 0xd6, 0xc4,
	0xfa, 0xd6, 0xdf, 0xe7, 0x4f, 0x93, 0x24, 0x2d, 0x45, 0x41, 0xbc, 0x4d, 0x86, 0x99, 0xc9, 0x97,
	0xc0, 0x85, 0x1b, 0x2c, 0xd9, 0xfa, 0xcd, 0x12, 0xca, 0x20, 0x79, 0xea, 0x75, 0x71, 0x73, 0xb0,
	0xf6, 0xd0, 0x61, 0x1d, 0xbc, 0xfd, 0xf1, 0xb5, 0x26, 0xd3, 0xe3, 0x07, 0x35, 0xbd, 0x8b, 0xb1,
	0xea, 0x8b, 0x41, 0xfa, 0x68, 0x09, 0xf9, 0x39, 0x24, 0x46, 0xe7, 0xac, 0x64, 0x62, 0xad, 0x12,
	0xa3, 0xf9, 0x15, 0x2c, 0xc8, 0x50, 0x87, 0x79, 0x52, 0x32, 0x91, 0xa9, 0x78, 0xe0, 0xd7, 0x90,
	0xb5, 0xb6, 0x77, 0x1d, 0x12, 0xea, 0xfc, 0xb4, 0x64, 0xe2, 0x4c, 0xcd, 0x06, 0xbf, 0x07, 0x68,
	0x07, 0x6c, 0x08, 0xf5, 0x4b, 0x43, 0x79, 0x5a, 0x32, 0xb1, 0xda, 0x14, 0x32, 0x22, 0xc8, 0x09,
	0x41, 0x3e, 0x4f, 0x08, 0x2a, 0x1b, 0xd3, 0x5b, 0xf2, 0xd5, 0xa3, 0xd3, 0x53, 0x75, 0xf1, 0x7f,
	0x75, 0x4c, 0x6f, 0xa9, 0xda, 0xc1, 0xda, 0xbf, 0x60, 0x17, 0xb6, 0x14, 0xbe, 0xcf, 0xe8, 0xec,
	0x4f, 0xf4, 0xe4, 0x17, 0xfa, 0xe6, 0x01, 0x56, 0x7e, 0xe4, 0x09, 0x87, 0x4f, 0xd3, 0x22, 0xbf,
	0x85, 0x65, 0xdc, 0xe3, 0x97, 0x32, 0x7c, 0xea, 0x8f, 0x1b, 0x0a, 0x98, 0xcd, 0xea, 0x64, 0xbf,
	0x0c, 0x7c, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x04, 0x81, 0x17, 0x66, 0x85, 0x01, 0x00,
	0x00,
}
