CREATE TABLE `voucher` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(64) NOT NULL,
	`discount` FLOAT UNSIGNED NOT NULL,
	`start` TIMESTAMP NOT NULL DEFAULT '',
	`end` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`),
	INDEX `code` (`code`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1535
;
