// Code generated by protoc-gen-go. DO NOT EDIT.
// source: week4/proto/data.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	week4/proto/data.proto

It has these top-level messages:
	CreatePersonRequest
	GetPersonRequest
	Person
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePersonRequest struct {
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Fullname string `protobuf:"bytes,3,opt,name=fullname" json:"fullname,omitempty"`
}

func (m *CreatePersonRequest) Reset()                    { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()               {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreatePersonRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

type GetPersonRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPersonRequest) Reset()                    { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()               {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPersonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Person struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Fullname string `protobuf:"bytes,3,opt,name=fullname" json:"fullname,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func init() {
	proto1.RegisterType((*CreatePersonRequest)(nil), "CreatePersonRequest")
	proto1.RegisterType((*GetPersonRequest)(nil), "GetPersonRequest")
	proto1.RegisterType((*Person)(nil), "Person")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PersonService service

type PersonServiceClient interface {
	CretePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*Person, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*Person, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) CretePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := grpc.Invoke(ctx, "/PersonService/CretePerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := grpc.Invoke(ctx, "/PersonService/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonService service

type PersonServiceServer interface {
	CretePerson(context.Context, *CreatePersonRequest) (*Person, error)
	GetPerson(context.Context, *GetPersonRequest) (*Person, error)
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_CretePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).CretePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PersonService/CretePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).CretePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CretePerson",
			Handler:    _PersonService_CretePerson_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _PersonService_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "week4/proto/data.proto",
}

func init() { proto1.RegisterFile("week4/proto/data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4f, 0x4d, 0xcd,
	0x36, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x33, 0x95,
	0x5c, 0xb9, 0x84, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x03, 0x52, 0x8b, 0x8a, 0xf3, 0xf3, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x29, 0x2e, 0x8e, 0xb4, 0xd2, 0x9c, 0x1c, 0xb0,
	0x38, 0x33, 0x58, 0x1c, 0xce, 0x57, 0x52, 0xe2, 0x12, 0x70, 0x4f, 0x2d, 0x41, 0x35, 0x83, 0x8f,
	0x8b, 0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88, 0x29, 0x33, 0x45, 0xc9, 0x83,
	0x8b, 0x0d, 0xa2, 0x00, 0x5d, 0x86, 0x54, 0xdb, 0x8c, 0xd2, 0xb8, 0x78, 0x21, 0x26, 0x05, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xe9, 0x70, 0x71, 0x3b, 0x17, 0xa5, 0xc2, 0x3c, 0x21, 0x24,
	0xa2, 0x87, 0xc5, 0x4f, 0x52, 0xec, 0x7a, 0x50, 0x69, 0x75, 0x2e, 0x4e, 0xb8, 0x63, 0x85, 0x04,
	0xf5, 0xd0, 0x1d, 0x0e, 0x57, 0xe8, 0xc4, 0x1e, 0xc5, 0x0a, 0x0e, 0xa5, 0x24, 0x36, 0x30, 0x65,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x31, 0x5c, 0xa5, 0x5a, 0x46, 0x01, 0x00, 0x00,
}
